version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /go/src/github.com/su-kun1899/chazuke
    steps:
    - checkout

    - run: go get -v -t -d ./...
    - run: go test -v ./...

    - codecov/upload:
        file: {{ coverage_report_filepath }}
