version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /go/src/github.com/su-kun1899/chazuke
    steps:
    - checkout

    - run: go get -v -t -d ./...
    - run: go test -v -race -coverprofile=coverage.txt -covermode=atomic

    - run: bash <(curl -s https://codecov.io/bash)
